--Vider les tables
DROP TABLE IF EXISTS "VEHICULE" CASCADE;
DROP TABLE IF EXISTS "AGENCE" CASCADE;
DROP TABLE IF EXISTS "CLIENT" CASCADE;
DROP TABLE IF EXISTS "UTILITAIRE" CASCADE;
DROP TABLE IF EXISTS "EMPLOYE" CASCADE;
DROP TABLE IF EXISTS "LOCATION" CASCADE;
DROP TABLE IF EXISTS "POSSEDER" CASCADE;
DROP TABLE IF EXISTS "CORRESPONDRE" CASCADE;
DROP TYPE IF EXISTS type_of_client;
DROP TYPE IF EXISTS type_of_employe;
