DROP TABLE IF EXISTS "VEHICULE" CASCADE;
DROP TABLE IF EXISTS "AGENCE" CASCADE;
DROP TABLE IF EXISTS "CLIENT" CASCADE;
DROP TABLE IF EXISTS "UTILITAIRE" CASCADE;
DROP TABLE IF EXISTS "EMPLOYE" CASCADE;
DROP TABLE IF EXISTS "LOCATION" CASCADE;
DROP TABLE IF EXISTS "POSSEDER" CASCADE;
DROP TABLE IF EXISTS "LOUER" CASCADE;
DROP TYPE IF EXISTS type_of_client;


--Ne sert à rien mais c'est joli.
--DELETE FROM "EMPLOYE";
--DELETE FROM "AGENCE";
--DELETE FROM "CLIENT";
--DELETE FROM "LOCATION";
--DELETE FROM "VEHICULE";
--DELETE FROM "UTILITAIRE";
--DELETE FROM "POSSEDER";
